### ISSUE TITLE
Ignore for lovelace-xiaomi-vacuum-map-Card

### ISSUE THREAD

**Issue by hagenuck1** [maykar/lovelace-swipe-navigation#14]
Hi, would be great if you could add support to ignore the „lovelace-xiaomi-vacuum-map-Card“
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

Thanks :)

**Comment by maykar** [comment]
This was added a while ago, but I forgot to close the issue. Thanks!
