### ISSUE TITLE
Immediate swipe without "empty" card

### ISSUE THREAD

**Issue by Devqon** [maykar/lovelace-swipe-navigation#26]
The animation in swipe first loads an "empty" card, and then slides the new view in. Is it possible to slide in the new view immediately next to the view that is swiped out?

I understand that then in fact there should always be 3 views loaded (the active one, the one left of it and the one right of it) but the animation would then seem and feel a lot more native.

**Comment by maykar** [comment]
As far as I am aware, there is no good method for me to load views that are not currently displayed. The current way that the swipe animation works is by sliding the view div off screen, navigating to the next view by simulating a click on the next/previous views tab, changing the position of the div to the opposite side, and then sliding it back in (it's just one element being tossed around). 

Some custom cards or even built in cards might take time to load or cause glitches, but in my experience (using a few custom cards with card-mod etc.) I don't experience any blank cards or strange animations.

When turning off the "swipe" animation, does the card in question load empty at first?

**Comment by Devqon** [comment]
Yeah sorry I misused some terms a bit. I mean it works exactly as you say and I do understand why, but it might be worth a try to preload the adjacent views to create the animation I suggested.

If I have some spare time I will give it a shot myself.

**Comment by maykar** [comment]
Always appreciate any help I can get. Though it has been a while, I attempted this quite a few times and it always came back to the fact that I could only have one view element present at a time. Preloading the next and previous pages didn't help unfortunately (at least what I tried) as the view element will still just rebuild when the next page is navigated to.

**Comment by maykar** [comment]
Ah I think I understand what you meant by card now. You mean the empty space that exists when the view is no longer on screen. One thing that helps with this illusion is to make sure that you set a background color that matches or is close to the background of your views, but yeah this is all just faking it for lack of a better option.

**Comment by mkrlearns** [comment]
Going to close this one for now, though I'd be happy to be proven wrong and will continue to attempt a solution myself.

**Comment by maykar** [comment]
Going to close this one for now, though I'd be happy to be proven wrong and will continue to attempt a solution myself.
