### ISSUE TITLE
FEATURE REQUEST: Auto Swipe Viewss

### ISSUE THREAD

**Issue by codeclinic** [maykar/lovelace-swipe-navigation#28]
Is there any possiblity that you could add a setting to have HA display each view in turn every x seconds? so it'd start at view 1 then open view 2 and so on on a defined time cycle.

Thanks.

**Comment by maykar** [comment]
This isn't something I'd add, but you can do this with [hass-browser-mod](https://github.com/thomasloven/hass-browser_mod). It has two features that would help you. You could use the [navigate](https://github.com/thomasloven/hass-browser_mod#navigate) feature to create an automation that would cycle through tabs or you could use the [blackout](https://github.com/thomasloven/hass-browser_mod#blackout) feature to prevent screen burn. 

Keep in mind that even though you're cycling through the tabs, there will still be elements that don't move and could cause burn in.
