### ISSUE TITLE
[REQ] may u add a custom_updater ?

### ISSUE THREAD

**Issue by MZorzy** [maykar/lovelace-swipe-navigation#3]
may u add the .json 
https://custom-components.github.io/custom_updater/Notes-for-developers
so will upgrade with custom updater and check with tracker-card . thnx

**Comment by maykar** [comment]
It's already there and instructions are in the readme.

https://github.com/maykar/lovelace-swipe-navigation/blob/master/README.md#installation-and-tracking-with-custom_updater

**Comment by MZorzy** [comment]
there is not the url cat (http) to put under
card_urls
