### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by xstrex** [maykar/lovelace-swipe-navigation#30]
Your documentation says that this feature is included in CCH, linked at the bottom of this page: https://github.com/maykar/lovelace-swipe-navigation/blob/master/info.md

This is not the case, if you go to the CCH documentation, and look at the important notes, it clearly states that you should use this repo for swipe navigation, linked here: https://maykar.github.io/custom-header/#intro/notes

So which is it? CCH clearly doesn't support swipe navigation, but this repo does. 

I'd be happy to put in a pull request to update the documentation, if you can validate which method is correct. 

Cheers.

**Comment by maykar** [comment]
Ah, right. When `Compact Custom Header` was replaced with `Custom Header` swipe navigation was removed. Looks like I just forgot to remove that note from the HACS info. Though technically it is still correct as it is included in `Compact Custom Header`, that project has just been deprecated. 😄

Updated info.md
