### ISSUE TITLE
HACS labels the plugin as not loaded

### ISSUE THREAD

**Issue by megawubs** [maykar/lovelace-swipe-navigation#32]
I've installed the plugin through HACS, but it keeps telling me that the plugin is not loaded. How to I make it to load?

![image](https://user-images.githubusercontent.com/2302867/89124116-bc910f80-d4d4-11ea-8936-76ebe0da9e06.png)

**Comment by megawubs** [comment]
I've got it loaded now, after a reinstall. But now it only works on the default view, and not on an additional lovelace view.

**Comment by maykar** [comment]
This is a known issue. This hasn't been updated since dashboards became a feature, but it should be fixed soon.

**Comment by maykar** [comment]
The reason HACS was saying it wasn't loaded was that the resource didn't exist. This is something that HACS usually does for you and reinstalling seemed to add the resource the second time around. As for why it didn't the first time, that's a question for the HACS forum post, discord, or github.

**Comment by maykar** [comment]
The multi-dashboard issue has been fixed in the latest release
