### ISSUE TITLE
Swipe an Climate Control doesn't work well together

### ISSUE THREAD

**Issue by richard-scott** [maykar/lovelace-swipe-navigation#35]
I have a Thermostat Card configured controlling a climate.

![image](https://user-images.githubusercontent.com/5149834/96375668-3e0e4a80-1172-11eb-8d00-9d3c3ef636c2.png)

With Swipe Navigation enabled, I'm unable to easily change the temperature on the orange part of this picture.
Most of the time Swipe Navigation takes over and swipes tabs.

Any ideas on how to fix this?

**Comment by KTibow** [comment]
You should disable `prevent_default`. You can also change `swipe_amount`.

**Comment by maykar** [comment]
This shouldn't be happening as the thermostat card is included in the [list of cards/elements](https://github.com/maykar/lovelace-swipe-navigation/blob/33d6ccb40dffc1985124ea8251099867422f8df9/swipe-navigation.js#L52) where swipe-navigation should be ignored.

Will look into it.

**Comment by maykar** [comment]
I can't replicate this. Not only are swipes ignored on the thermostat card by default, but they are ignored on the slider element it uses as well.

What is your swipe nav config?

**Comment by richard-scott** [comment]
Hmmm, it seems ok for me today... maybe I had phat fingers ;-(

I've just tried and checked my settings and they are these:
```
swipe_nav:
  wrap: true
  animate: swipe
  prevent_default: true
  swipe_amount: 50
```

I think we can close this one now as a false positive.
