### ISSUE TITLE
Is this still working in v117

### ISSUE THREAD

**Issue by erikwachters** [maykar/lovelace-swipe-navigation#38]
I can't get it to work in v117.
I've did a copy paste of the example but nothing happens.

**Comment by maykar** [comment]
Yes this is working in 0.117, it was updated for it a few hours ago. The current version that was updated for HA v0.117 is v1.2.7.

* How did you install: with HACS or manually?
* If you installed manually, did you copy from the raw link in the instructions or did you copy paste from elsewhere?
* Why did you copy and paste the example when it warns you not to?
* If you remove your swipe_nav config so that it just uses the default values, does it work?
* Do you get any errors in your HA logs or in your browsers dev tools (F12)?
* What version of swipe_navigation are you using?

**Comment by erikwachters** [comment]
Hello,

- Installation via HACS
- Sorry, I didn't exactly copy, this is the section in config:

```
swipe_nav:
  animate: swipe
  swipe_amount: 30

```
- If I remove the config, it doens't work
- no errors in dev tools
- v1.2.7

**Comment by maykar** [comment]
Does the resource exist either in `ui-lovelace.yaml` or in `configuration > lovelace dashboards > resources`?

What device are you using and have you cleared cache?

On iPhone companion app this can be difficult and can require many refreshes of the page.
On Android companion app, close app, hold app icon, select app info, select storage & cache, clear cache.

**Comment by damanti-me** [comment]
Yes, for iPhone you need to clear the cache in the settings. Then it's working :)

**Comment by maykar** [comment]
@damanti-me Out of curiosity, is that a setting in the iPhone companion app or is there a place in iPhone settings to clear app cache? Would be useful to know so I can point folks in that direction when needed.

**Comment by damanti-me** [comment]
@maykar 
1. open the iPhone app "Home Assistant" by Nabu Casa
2. open the menu
3. scroll down to _app configuration_
4. scroll down to _reset Frontend Chache_

edit: i also restarted the app after this

**Comment by maykar** [comment]
Perfect, thank you!

**Comment by maykar** [comment]
Perfect, thank you!

**Comment by KTibow** [comment]
@maykar was that double-comment on purpose?

**Comment by maykar** [comment]
What double comment 😜...nope, just poor connection and a itchy trigger finger I guess.

**Comment by erikwachters** [comment]
What do yu mean with this:

> Does the resource exist either in ui-lovelace.yaml or in configuration > lovelace dashboards > resources?

I use Android & chrome o Windows. I cleared the cache, no joy.

**Comment by maykar** [comment]
I'm going to assume you're not using YAML mode here:

Go to your sidebar and click on "Configuration", then click on "Lovelace Dashboards", then on "Resources".
Do you see something like this `/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js` in there?
If not, then click the plus icon, add `/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js` in the URL field and hit "create".

HACS should automatically do this for you, but there have been occasions where it has not.

**Comment by erikwachters** [comment]
> I'm going to assume you're not using YAML mode here:

I'am in yaml mode. :)

I added this to my recources, correct?

  - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
    type: module

**Comment by maykar** [comment]
That's the right resource and just in case, how to add resources in yaml mode:

https://www.home-assistant.io/lovelace/dashboards-and-views/#adding-more-dashboards-with-yaml

Then in top right menu while on a lovelace page select "Reload resources"

**Comment by erikwachters** [comment]
Got it.
For some reason I put the resources section in the lovelace.yaml iso configuration.yaml and that did the trick.
Strange that this is the first time I have troubles with this.

Anyway, thanks for the support!!
