### ISSUE TITLE
Errors messages in HA log

### ISSUE THREAD

**Issue by DJTerentjev** [maykar/lovelace-swipe-navigation#41]
Could you please check. I have periodical errors in HA log:

..../lovelace-swipe-navigation/swipe-navigation.js:19:75 TypeError: t.shadowRoot.querySelector(...) is null']

I have last version of HA and last 1.3.0 swipe-navigation. No addition configuration.

**Comment by KTibow** [comment]
This is actually a problem that should show up in the browser console. You might need to upgrade HA and swipe-navigation.

**Comment by maykar** [comment]
If you're on the latest version of both and still getting those errors you probably need to clear the cache of the app/browser of all devices that use this, if you installed manually be sure to add to the version number at the end of the resource URL.

**Comment by DJTerentjev** [comment]
Thank you for fast response. I reinstalled swipe-navigation and cleared cash all devises I am using. After that successfully tested on all devises. No errors so far. I'll close this issue.  Thanks for development such future!
