### ISSUE TITLE
Integration 'swipe_nav' not found.

### ISSUE THREAD

**Issue by realjax** [maykar/lovelace-swipe-navigation#44]
Hi,

Getting this error message:
`Component error: swipe_nav - Integration 'swipe_nav' not found.`

when using 
```
swipe_nav:
  animate: swipe
```
in configuration.yaml.  The integration does work though.

What am I missing?

**Comment by maykar** [comment]
Swipe Nav config doesn't happen in configuration.yaml, it is added to your lovelace config either by using the raw config editor or if you use YAML mode it goes in ui-lovelace.yaml
