### ISSUE TITLE
Stops working after a period (last good version 1.2.9)

### ISSUE THREAD

**Issue by smithbill17** [maykar/lovelace-swipe-navigation#45]
I've reinstalled Swipe Navigation using HACS and initially tried the latest release v1.3.0. After a period of time (and possibly after exiting the Home Assistant front end & relaunching it) the swipe navigation stops working.

The swipe navigation seems to fail using the browser interface (Android Chrome) and also in the native Android Home Assistant app from the Google Playstore.

I tried every beta version up to the latest v1.3.3, and they all failed after a while.

The last 'good' version which doesn't seem to fail, is v1.2.9

**Comment by smithbill17** [comment]
Latest v1.3.5 seems to have fixed this problem - so I'll close this issue.

**Comment by maykar** [comment]
Appreciate the update and glad to hear it fixed it for you.
