### ISSUE TITLE
Swipe not work with grafana iframe

### ISSUE THREAD

**Issue by radeon79** [maykar/lovelace-swipe-navigation#46]
I have a iframe card (with a url of a dashboard of grafana) with view in panel mode. In this case the swipe is not work (for this tab only).
Is possible to solve???

**Comment by KTibow** [comment]
Does `prevent_default` help?

**Comment by radeon79** [comment]
unfortunately no

**Comment by KTibow** [comment]
Anything can't go inside iframes. My best idea would to be to set the z-index of the iframe to a low amount.

**Comment by radeon79** [comment]
How to set this option? Note: This problem is for app and for browser.

**Comment by KTibow** [comment]
card-mod.

**Comment by radeon79** [comment]
Ok thanks for this suggestion. I test this solution. Please close this ticket.
