### ISSUE TITLE
Swipe navigation not working on Android

### ISSUE THREAD

**Issue by willheineman** [maykar/lovelace-swipe-navigation#47]
I recently upgraded to 1.3.5 any swipe navigation is no longer working. It has previously worked for the last few versions.

I use the home assistant Android app and have reloaded multiple times. Sometimes it does work for a couple minutes, but then becomes unresponsive and I can no longer swipe between dashboards. Normally doing a reload does enable it to work again. But it always stops after a few minutes.

I use the default swiping configuration and I do not have any configurations in my Lovelace dashboard.

Samsung Galaxy S20
Android 11
Home Assistant 2021.1.0

**Comment by KTibow** [comment]
Logs? Does it work on a computer?

**Comment by maykar** [comment]
As KTibow mentions: check your logs for any errors and report them here. Also, while on a computer make sure the latest version is installed by opening your browser's dev tools console (F12) and checking what version is displayed there as well as any errors pertaining to swipe-navigation, and on the android device make sure you have cleared the app's cache by following the steps below:

* Hold app icon and select "App Info"
* Click "Force Stop"
* Click "Storage and Cache"
* Click "Clear Cache"
* Reopen app

**Comment by willheineman** [comment]
Thanks. I will test on a PC and browser, then try to pull logs I am not seeing any errors in the logs, but I will look more closely. I just downgraded it and things seem to work fine for now.
