### ISSUE TITLE
No swipe navigation in HACS

### ISSUE THREAD

**Issue by Philou06** [maykar/lovelace-swipe-navigation#49]
Hi,

I would like to install this with HACS but he doesn't found "swipe navigation", some help please?

![image](https://user-images.githubusercontent.com/81933852/113523987-ef336080-95ab-11eb-93a7-00d644702af4.png)

Thank you

**Comment by maykar** [comment]
![image](https://user-images.githubusercontent.com/25127328/113524045-11ac8600-957a-11eb-8713-06064cca089c.png)

If I can see HACS on your screenshot, you're in the wrong place.

**Comment by Philou06** [comment]
Ok thank you and sorry, this is the first time I use HACS :-)
