### ISSUE TITLE
compatibility for Ariela App

### ISSUE THREAD

**Issue by Underknowledge** [maykar/lovelace-swipe-navigation#6]
I use Ariela as mobile client. 
Sadly the swipe navigation does'nt work in there.
I guess you use the user agent like in the cca Conditional Styling.

(Ariela)
`
Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36 
`

This one works.
(Chrome on phone )
`
Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36
 `

**Comment by maykar** [comment]
I do not limit by user agent. If it doesn't work in Ariela you would need to talk to the developer. Also, it looks like Ariela implemented it's own swipe navigation on the latest version.

**Comment by Underknowledge** [comment]
too slow - Thanks a ton for this killer feature!
