### ISSUE TITLE
Problem setup Home Assistant 2021.12.8

### ISSUE THREAD

**Issue by Mick51** [maykar/lovelace-swipe-navigation#65]
Hello, I installed the addon on the latest version of Home Assistant 2021.12.8, I cleared the cache of all the applications that are in version 2022.1.1 and the browser. But despite this, it doesn't work.......

**Comment by KTibow** [comment]
Can you please make more effort with your issue, and provide things like how you installed it, browser console logs, etc?

**Comment by Mick51** [comment]
The application does not report any particular bug but after installation nothing happens.  I will look more at the logs but I did not find anything concerning this ....

**Comment by jmound** [comment]
@Mick51 I installed and it didn't work, then I uninstalled, resarted HA, reinstalled, restarted HA again, and it works now. I don't have any information as to why.

**Comment by Mick51** [comment]
> @Mick51 I installed and it didn't work, then I uninstalled, resarted HA, reinstalled, restarted HA again, and it works now. I don't have any information as to why.

Thank you very much this worked for me too .... 😉👌
