### ISSUE TITLE
Best background image and settings for Animate config option?

### ISSUE THREAD

**Issue by jerrychong25** [maykar/lovelace-swipe-navigation#8]
Hi,

I noticed there is Animate config option in latest version today.

Just curious, what is the best background image and settings for Animate config option?

In my case, I used dark blue background, but when animation it will pop up gray background. So not a good result.

If able to achieve similar to screenshot below (Animation is previous/next tab details), will be very nice:
![Capture](https://user-images.githubusercontent.com/15714095/57378771-132b7300-71d8-11e9-8eee-ab0e9fc93b22.PNG)

Thanks.

**Comment by maykar** [comment]
I’m “cheating” to achieve the scrolling effect. The view element swipes off screen, navigates to next view (in the same element), then it quickly jumps to the other side of the screen and moves in. This just gives the illusion one is swiping out and the other is swiping in, but in fact its just the same element being thrown around while the contents are changing. What you are seeing during the swipe is the background-color from the home assistant theme being shown as there is no background image on the element below.

I believe this is the only way that I can achieve a swiping animation with an addon to lovelace. There may be other ways for me to cheat the system or improve the effect (like adding a background image to the lower element or fading the view in and out while swiping), but I don't think the animation will ever be without quirks.

**Comment by maykar** [comment]
Currently this looks best when using the same background-color in your view as in your HA theme with no background image.

Ideally I should be trying to add things like these to the HA core as I would be able to add something like this without "cheating", but am dragging my feet getting a dev environment set up and making my first PR to HA. I don't have a ton of free time, but really do enjoy making these things and plan to help with HA's development in what little way I can.

**Comment by jerrychong25** [comment]
> Currently this looks best when using the same background-color in your view as in your HA theme with no background image.
> 
> Ideally I should be trying to add things like these to the HA core as I would be able to add something like this without "cheating", but am dragging my feet getting a dev environment set up and making my first PR to HA. I don't have a ton of free time, but really do enjoy making these things and plan to help with HA's development in what little way I can.

Thanks for the info.

Doing in this way will sacrifice my background image which I cannot do.

So probably cant use this same background colour as HA theme method to solve my issue.

Do you found any other contributor that achieve similar things?

As this plugin is compatible with [Swipe Card](https://github.com/bramkragten/custom-ui/tree/master/swipe-card), is this can use on swiping between tab? If yes, I think this might solve this issue with background image.

**Comment by maykar** [comment]
I believe this is something that would need to be added to HA core and not entirely possible as an addon or card. Swipe card can do this as it's not modifying anything outside of it's own card.

**Comment by jerrychong25** [comment]
> I believe this is something that would need to be added to HA core and not entirely possible as an addon or card. Swipe card can do this as it's not modifying anything outside of it's own card.

Noted and thanks.
