### ISSUE TITLE
Local custom_updater/Tracker_card - not displaying

### ISSUE THREAD

**Issue by Tom-ahawk** [maykar/lovelace-swipe-navigation#9]
Create card!

I am not sure that this is an issue, but this card behaves differently than other cards for custom updater/Tracker_card..
When using this, custom_updater/Tracker_card behaves as expected.
  - type: js
    url: /customcards/github/maykar/lovelace-swipe-navigation.js?track=true

When using this, its not displayed in custom_updater/Tracker_card. 
  - type: js
    url: /local/custom-lovelace/lovelace-swipe-navigation.js

The thing is, other cards are displayed correctly in the custom_updater/Tracker_card, using 
  url: /local/custom-lovelace/…

How come it does not works for local location?

**Comment by maykar** [comment]
Is this still an issue if you use `?track=true` on your second example? If it is still an issue, the difference might just be the fact that some cards are included in custom_updater by default like the ones in the [custom-cards repo](https://github.com/custom-cards) and a handful of other popular projects, but you should use the example as shown in the readme and your first example as it avoids caching issues.

**Comment by Tom-ahawk** [comment]
I am afraid the "/local/custom-lovelace/lovelace-swipe-navigation.js?track=true" makes the card disappear from the custom_updater/Tracker_card.

I have a lot of custom cards working fine, not only cards in the custom-card repo:
![image](https://user-images.githubusercontent.com/35527507/57536410-6b7f8380-7344-11e9-908f-a5a657920def.png)

**Comment by maykar** [comment]
Did you also list the card's URL in the the custom_updater component config under card_urls?
https://custom-components.github.io/custom_updater/Installation#configuration-option-card_urls

Regardless, use the method that is in the readme for this project and everything works as intended, there is no advantage I can see to using the local URL . The github URL avoids the need for adding a card URL  to the component and prevents caching issues.

**Comment by Tom-ahawk** [comment]
Aha,- I did not see that in your documentation: What’s the correct URL to us for the card_urls?
We N00bs have to have it spelled out ; )

I have been wondering about that. I believed using local storage of the code, minimized network traffic and the card code always present for HA?

**Comment by maykar** [comment]
custom_updater downloads the card and updates to your local install, the only time it uses network traffic is to check for updates and download/update the card when you click update.

**Comment by maykar** [comment]
If you still want to use the local method use this URL, but again, there is no advantage to doing so. Both methods use the card locally.

`https://raw.githubusercontent.com/maykar/lovelace-swipe-navigation/master/tracker.json`

**Comment by Tom-ahawk** [comment]
I appreciate your patients. Thanks!

Local works fine now, and without the "?track=true"
